### ISSUE TITLE
The output of default example is wrong

### ISSUE THREAD

**Issue by LLSean** [redotvideo/revideo#147]
I used the default template to render the video and downloaded the video. The output is below.

<img width="1233" alt="image" src="https://github.com/redotvideo/revideo/assets/1560188/1e5ce991-5f07-48d0-889e-2fdc37532b96">

**Comment by justusmattern27** [comment]
@LLSean thanks for pointing this out! You can get a correct output when first fetching a github repository (say redotvideo/pluto), but nonetheless, the default should of course also be correct. I will start working on a fix today.

**Comment by hkonsti** [comment]
Thanks for flagging! This will be fixed with the next release.
