### ISSUE TITLE
When <Player /> is paused, audio from earlier scenes continues playing

### ISSUE THREAD

**Issue by ansonkao** [redotvideo/revideo#172]
For example, if you have Scene A and Scene B. Scene A has an audio clip that is longer enough to cover Scene B as well. If the playhead is on scene B when the pause button is pressed, the audio continues to play.

**Comment by ansonkao** [comment]
When rendering, the audio from Scene A cuts off as soon as transitioning to Scene B. So there is a discrepancy... which behaviour is expected?

**Comment by hkonsti** [comment]
It should cut off, so the player behavior needs to be fixed. We'll look into it, thanks for reporting! As a temporary fix, you could manually pause and remove all audio files using a ref like this:
```tsx
audioRef.pause();
audioRef.remove();
```

**Comment by justusmattern27** [comment]
this is fixed by #188 - will be part of 0.4.7 (releasing it right now!). Feel free to reopen if any issues arise

**Comment by NerminKarapandzic** [comment]
Hey @justusmattern27 I was looking for issues regarding Transition API, and I stumbled upon this issue, and I think it's relevant to ask this here:

The fix you mentioned will stop the audio when the scene ends; it assumes we use multiple scenes. I haven't seen any examples of how to actually use multiple scenes in a project.

But to clarify, I want to create scenes programatically, not hardcode.

This would allow me to use the Transition API.
Is this possible, and are there any examples of it?

Also, in the event this is possible, would it also be possible to define scene-specific variables?
