### ISSUE TITLE
Suport for Rive animations

### ISSUE THREAD

**Issue by tslater** [redotvideo/revideo#179]
The last thing we'd need to switch over from Remotion is support for Rive animations::
https://www.remotion.dev/docs/rive
https://rive.app/

This allows us to do really complex animations, transitions, etc. in remotion and would be an awesome addition to revideo!

**Comment by hkonsti** [comment]
We're currently looking into this!

**Comment by justusmattern27** [comment]
Cool to see so many people upvoting this! Revideo's v0.5.2 contains a first version of our `<Rive />` component from the `@revideo/2d` package. You can now use Rive animations as such:

```tsx
yield view.add(
      <Rive
        src={"https://revideo-example-assets.s3.amazonaws.com/emoji.riv"}
        animationId={1}
        size={[600, 600]} 
        opacity={0}
        ref={riveRef}
      />
);
```

A full example can be found here: https://github.com/redotvideo/examples/tree/main/rive-explanation-video


You can use the parameters `animationId` and `artboardId` to choose a specific animation to display (both accept strings and numbers, so you can choose by name or index). This first implementation seems to work well and using Rive's Javascript runtime was easy, but I admit that I'm not an expert of the **Rive app** at all and don't fully understand the needs of users that build animations with Rive.

Therefore, if anything is lacking in this implementation, please let me know here! I will keep the issue open for now and would love your feedback! If anyone who wanted this feature is willing to talk to me about their needs with Rive, please let me know. Thanks!

**Comment by justusmattern27** [comment]
so far, Rive animations work for me and I haven't heard any complaints. Closing this issue now, feel free to reopen if you run into issues
