### ISSUE TITLE
Rendering video... .... [vite] error while updating dependencies: Error: EBUSY: resource busy or locked, rename ...

### ISSUE THREAD

**Issue by ullenboom** [redotvideo/revideo#181]
Unfortunately, I am getting an error for a brand-new project. What I did:

```
npm init @revideo@latest
npm i
npm run render
```

I got:

```
Rendering video...
.... [vite] error while updating dependencies:
Error: EBUSY: resource busy or locked, rename '...\revideo\node_modules\.vite\deps_temp_5a9f13d3' -> '...\revideo\node_modules\.vite\deps'
```

The process is blocked, and no video is being generated. I'm using Node.js version v20.15.0. The package.json file specifies an older version of Vite, resulting in the use of Vite 4.5.3.

**Comment by justusmattern27** [comment]
@ullenboom Thanks for reporting this! I have never encountered this so far so I can't really reproduce. It seems like the vite cache is blocked for some reason. Could you try deleting the `./vite` folder and re-running the command?

**Comment by ullenboom** [comment]
I've identified the root cause of the issue: it's Dropbox. The synchronization process appears to be causing a blockage. After pausing Dropbox, everything is working smoothly again.

**Comment by justusmattern27** [comment]
@ullenboom that's an interesting fix! 😅
