### ISSUE TITLE
Audios with a lower playback rate get cut off

### ISSUE THREAD

**Issue by Pita** [redotvideo/revideo#208]
Had an <Audio> Element with a playbackRate of 0.75. The audio does not fully get played, it suddenly stops. I guess the duration of the audio does not properly get calculated and therefore gets suddenly cut off.

**Comment by justusmattern27** [comment]
thanks for the pointer! I'm looking into this

**Comment by justusmattern27** [comment]
#216 fixes this and will be part of the next release - I'm closing this issue for now, feel free to reopen if the problem persists for you!
