### ISSUE TITLE
Some videos hang with web decoder

### ISSUE THREAD

**Issue by diogeneshamilton** [redotvideo/revideo#222]
I believe I've found an issue with the web decoder. It only happens on some videos, and only happens in the Lambda environment, probably because it's a different decoder in the Amazon Linux environment than on Mac. What's frustrating is it just hangs and times out, there's no error thrown. 

Here's a couple videos where it hangs consistently (I have verified that switching to decoder='ffmpeg' on the Video element fixes the issue, but of course, we lose speed):
https://jelly-shareables.s3.amazonaws.com/for-revideo-founders/1c49f2e1-0b86-4a38-803b-dac6f6494ae7-video.mp4
https://jelly-shareables.s3.amazonaws.com/for-revideo-founders/f1ecf53e-81f2-49cf-a5d6-6fe50af6256e-video.mp4

**Comment by hkonsti** [comment]
Hey, thanks for flagging! We were able to reproduce this with the video and scene code you provided on Discord. I think I have identified the issue and will work on a solution now. I'll get back to you as soon as I have something!

**Comment by diogeneshamilton** [comment]
Thank you!
