### ISSUE TITLE
Audio mounted slightly wrong causes volume to get increasingly louder

### ISSUE THREAD

**Issue by Pita** [redotvideo/revideo#234]
Reproduced it with this code, which forgot a yield:
```
import {Audio, makeScene2D} from '@revideo/2d';
import {waitFor} from '@revideo/core';

export default makeScene2D(function* (view) {
  for (let i = 0; i < 100; i++) {
    const x = <Audio src="/sounds/iphone.wav" play={true} />;
    view.add(x); // forgot the yield here
    yield* waitFor(1);
  }
});
```

This creates this warning actually: 
```
Worker 0: JSHandle:warning from browser process:
Worker 0: JSHandle:Tried to access an asynchronous property before the node was ready. Make sure to yield the node before accessing the property.
```

This causes the audio to get increasingly louder

![Screenshot 2024-08-03 at 17 00 19](https://github.com/user-attachments/assets/0e0a5aa8-41cb-4e8a-9ff1-56af1c309173)

You might say user error, and feel free to just close this. Just thought it's worth documenting as I spent some time debugging this and might not be the only one to run into this issue. 

Btw, the audio will play if you just construct an <Audio> object. You don't even need to add it to the view. You can skip that line altogether.

**Comment by justusmattern27** [comment]
this is definitely interesting, thanks for the pointer. Audio nodes should indeed be yielded - any in which we await promises has to, e.g. also Txt nodes because we need to await fonts to load here. I'll take a look

**Comment by Pita** [comment]
This one was also fixed by my fix
