### ISSUE TITLE
Provide an option to configure FPS

### ISSUE THREAD

**Issue by Pita** [redotvideo/revideo#238]
I noticed that from 0.3 to 0.5, the FPS got raised to 60. This is way more than I need for my kind of videos and just slows down the render process needlessly. I can't find a place to configure the FPS. Can you please add an option to the renderVideo function?

**Comment by justusmattern27** [comment]
this can be adjusted through your `project.meta` file. Have you already tried modifying this?

**Comment by justusmattern27** [comment]
talked about it on Discord - setting fps in project.meta works, therefore closing this issue :)
