### ISSUE TITLE
be able to mute the player programmatically and have a control for it

### ISSUE THREAD

**Issue by diogeneshamilton** [redotvideo/revideo#282]
- prop `volume` or `muted` on `<Player>`
- controls includes a sound on off button, or volume slider with mute

**Comment by justusmattern27** [comment]
thanks for the suggestion! I agree that this should definitely be added, we'll take a look at this soon

**Comment by justusmattern27** [comment]
@diogeneshamilton this is part of 0.5.10, feel free to reopen if you notice any issues!
