### ISSUE TITLE
HLS input video support

### ISSUE THREAD

**Issue by tslater** [redotvideo/revideo#46]
I need HLS support. Specifically, I want to grab shorter clips from longer videos without necessarily needing to download the whole thing.

**Comment by justusmattern27** [comment]
@tslater thanks for the feedback! You've probably already seen that you can use remote urls in the README, e.g.:

```tsx
yield view.add(
      <Video
        src={'https://revideo-example-assets.s3.amazonaws.com/stars.mp4'}
        size={['100%', '100%']}
        play={true}
      />
  );
```

This will not (directly) download the entire file either unless you're going to play all of it. I assume that you want support for .m3u8 files, correct?

**Comment by tslater** [comment]
That's correct. Or Dash/mpd  is that easier. We use CMAF which supports
both.

**Comment by justusmattern27** [comment]
got it, I'll look into this!

**Comment by diogeneshamilton** [comment]
I'm interested in this as well!

**Comment by tslater** [comment]
@justusmattern27 Big deal. Thanks a bunch! We'll check it out!

**Comment by justusmattern27** [comment]
closing this now - if you run into any issues, feel free to re-open :)
