### ISSUE TITLE
Using Revideo to render single or multi frames as image

### ISSUE THREAD

**Issue by mnlbox** [redotvideo/revideo#49]
Hi,

Is there any way to render a specific frame as an image or a range of frames (in video or image sequence mode) rather than entire video?

**Comment by justusmattern27** [comment]
Yes, there is - in your `project.meta` file, you can edit the `range` parameter. By default, it will look like this:

```
    "range": [
      0,
      null
    ],
```

If you want to export a video from second 0 to 3 only, you can change it to 

```
    "range": [
      0,
      3
    ],
```

Currently, you can not yet add the range as a parameter for `renderVideo()`, but I'll start working on this today.

**Comment by mnlbox** [comment]
Thanks @justusmattern27,

I'll check it. And can I use same approach to render a single still image as well?
To use Revideo as an engine for creating images programmatically rather than video

**Comment by hkonsti** [comment]
Yes you can! Just set the range to [0,1]. Feel free to reopen if there are any more questions :)

**Comment by Mirahlee** [comment]
your posts are worth reading, though we are not following each other, please kindly follow back, I want us to be friends and you can share some of your thoughtful ideas with me. Thanks
