### ISSUE TITLE
some animations in documentation are broken

### ISSUE THREAD

**Issue by mnlbox** [redotvideo/revideo#51]
I just realised some animations in documentation are broken, for example:
https://docs.re.video/nodes

<img width="1261" alt="image" src="https://github.com/redotvideo/revideo/assets/25859075/df29080e-0c73-45f2-bbdb-9b8095040aa2">

**Comment by hkonsti** [comment]
thanks for flagging this. i'm going to look into it!

**Comment by hkonsti** [comment]
this is fixed now :)

**Comment by mnlbox** [comment]
Thanks @hkonsti ,

Most of them are fixed but as I checked randomly still some animations not working in the docs. For example, the second animation here in this link is shown as a still image without any movement:
https://docs.re.video/spline
<img width="1323" alt="image" src="https://github.com/redotvideo/revideo/assets/25859075/c3b1c7fb-2dcd-4e15-8800-6aa0a10db2be">
or here:
<img width="1323" alt="image" src="https://github.com/redotvideo/revideo/assets/25859075/9fd3448b-f60a-4cf1-abe5-a498042b0d10">

**Comment by mnlbox** [comment]
Some of the source code links are also broken in the doc, for example:
![image](https://github.com/redotvideo/revideo/assets/25859075/bf1733b0-9997-4d3a-a0a4-a22db4d421b3)

This link refers to the url below that is not a valid url:
https://github.com/revideo/revideo/blob/main/packages/examples/src/scenes/layout.tsx

**Comment by mnlbox** [comment]
Another small issue here:
<img width="1341" alt="image" src="https://github.com/redotvideo/revideo/assets/25859075/46076db3-29cf-4ba4-92e2-33023e16d9ce">

Showing "Runtime error" here in this page:
https://docs.re.video/layouts

**Comment by mnlbox** [comment]
@hkonsti 
@justusmattern27 
Maybe we can keep this issue open then we can collect and track all the broken links/bigger docs issues here.
